Transform: AWS::Serverless-2016-10-31
Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        HelloGfmiApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref MyApi
            Auth:
              Authorizer: CognitoAuthorizer