AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        openapi: "3.0.0"
        info:
          title: My API
          version: "1.0"
        paths:
          /my-resource:
            get:
              responses:  
                '200':
                  description: Successful response
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                '400':
                  description: Bad Request
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          error:
                            type: string
              x-amazon-apigateway-integration:  
                type: aws_proxy  
                httpMethod: POST
                uri: !Sub
                  - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations
                  - FunctionArn: !GetAtt MyFunction.Arn

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /newlocation
            Method: GET  