AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Resources:
  
  MyEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: my-event-bus

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      InlineCode: |
        exports.handler = async (event, context) => {
          return {
            statusCode: 200,
            body: JSON.stringify({
              message: "hello world",
            }),
          };
        };
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Name: !Sub "${AWS::StackName}-my-rule"
            EventBusName: !Ref MyEventBus
            Pattern:
              detail-type: ["FooBar"]