Transform: AWS::Serverless-2016-10-31
Resources:
  api:
    Type: 'AWS::Serverless::Api'
    Properties:
      Cors: www.example.tld
      StageName: v1
      DefinitionBody:
        openapi: 3.0.1
        info:
          version: 0.0.1
          title: example
        paths:
          /mypath:
            get:
              responses:
                '200':
                  description: Default response
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${someFunction.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: GET
                type: aws_proxy