AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

Resources:
  OnePolicyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: python3.9
      Policies: "SESBulkTemplatedCrudPolicy_v2"