AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals: 
  Function:
    Timeout: 15
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  BlastDbUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageConfig:
        Command:
        - blast-db-updater.lambda_handler
      ImageUri: 123456789012.dkr.ecr.region.amazonaws.com/repository:tag
    Events:
      Trigger:
        Type: EventBridgeRule 
        Properties:
          RuleName: OnBatchJobStateChange
          Pattern:
            source:
              - aws.batch
            detail-type:
              - Batch Job State Change                
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.11-v1