Transform: AWS::Serverless-2016-10-31
Resources:
  xyzfunction:         
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "xyz"                                                                
      Description: ""
      Handler: xyz::xyz::FunctionHandler                   
      CodeUri: ./xyz-app.zip
      Runtime: dotnetcore3.1
      Environment: 
        Variables:
          ASPNETCORE_ENVIRONMENT: !Ref Stage
      EphemeralStorage: 5000