AWSTemplateFormatVersion: '2010-09-09'
Transform: AW::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: main.handler
      Runtime: python3.8