AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Description: Test SAM App
    Name: test-sam-app
    Author: Developer
    ReadmeUrl: README.md
    SemanticVersion: 0.1.0

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: /test/parameter