AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyServerlessAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: VerifyIAMAuthorizer
        Authorizers:
          VerifyIAMAuthorizer:
            FunctionArn: !GetAtt IamAuthorizerFunction.Arn

  IamAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cmd/authorizer

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cmd/test
      Events:
        APIRequest:
          Type: Api
          Properties:
            RestApiId: !Ref MyServerlessAPI
            Path: /
            Method: get