Transform: AWS::Serverless-2016-10-31
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      AlwaysDeploy: true
      StageName: prod
      Models:
        mybody:
          type: object
          properties:
            myprop:
              type: string
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          return {"statusCode": 200, "body": "hi"}
      Events:
        MyEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref MyApi
            RequestParameters:
              - method.request.querystring.myquerystring:
                  Required: true
              - method.request.header.myheader:
                  Required: true
            RequestModel:
              Model: mybody
              ValidateBody: false
              ValidateParameters: true
Outputs:
  ApiEndpoint:
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/"