AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Description: "Some description"
      DisableExecuteApiEndpoint: True

  LambdaFunctionExample:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'foo': 'bar'}
      Events:
        HttpProxyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /{proxy+}
            Method: ANY