AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  apigateway-2402

  Sample SAM Template for apigateway-2402

Resources:
            
  ApiGatewayAdminOne:
    Type: AWS::Serverless::Api
    Properties:
      Name: App-Prod-Web-One
      StageName: Prod
      TracingEnabled: true
      MethodSettings:
        - LoggingLevel: Info
          ResourcePath: '/*'
          HttpMethod: '*'
      Domain:
        DomainName: admin.one.amazon.com
        CertificateArn: arn::cert::abc
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: "abc123456"


            
  ApiGatewayAdminTwo:
    Type: AWS::Serverless::Api
    Properties:
      Name: App-Prod-Web-Two
      StageName: Prod
      TracingEnabled: true
      MethodSettings:
        - LoggingLevel: Info
          ResourcePath: '/*'
          HttpMethod: '*'
      Domain:
        DomainName: admin.two.amazon.com
        CertificateArn: arn::cert::abc
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: "abc123456"

        
            
  ApiGatewayAdminThree:
    Type: AWS::Serverless::Api
    Properties:
      Name: App-Prod-Web-Three
      StageName: Prod
      TracingEnabled: true
      MethodSettings:
        - LoggingLevel: Info
          ResourcePath: '/*'
          HttpMethod: '*'
      Domain:
        DomainName: admin.three.amazon.com
        CertificateArn: arn::cert::abc
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: "abc123456"
