AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  APIStage:
    Default: dev
    Description: Name of the API stage to use for deployment
    Type: String
    AllowedPattern: '[A-Za-z0-9-]*'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          APIStage: !Ref APIStage