AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Resources:
  
  MyEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: my-event-bus

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      # InlineCode: ...
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            RuleName: !Sub "${AWS::StackName}-my-rule"
            EventBusName: !Ref MyEventBus
            Pattern:
              detail-type: ["FooBar"]