AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref CommonDependenciesLayer

  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: 'dev-common-dependencies-layer'
      Description: 'Common dependencies for dev env'
      ContentUri: './dependencies'
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs14.x