AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  S3ListenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Runtime: python3.10
      Handler: app.handler
      Architectures:
        - x86_64
      Description: "Listen to S3"
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-zizera-sam
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true
Outputs:
  S3ListenerFunction:
    Description: S3 Listener Function ARN
    Value: !GetAtt S3ListenerFunction.Arn