AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 162abd93-8c3f-4ca3-b554-3aa439a45f20
      Runtime: python2.7
      Handler: service.handler
      MemorySize: 1024
      Timeout: 30
