Transform: AWS::Serverless-2016-10-31
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: unzip-v1
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 4a24c713-71ef-402a-8b02-723937c2530d
      CompatibleRuntimes:
      - python3.8
      - python3.7
      - python2.7
Outputs:
  LayerArn:
    Value:
      Ref: SharedLayer