AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LayerName:
    Type: String
    
    
Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-layer-headless-chromium
    Description: "AWS Lambda Layer for Headless Chromium"
    Author: Pahud Hsieh
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['layer','lambda','chrome','headless', 'aws']
    HomePageUrl: https://github.com/pahud/lambda-layer-headless-chromium
    SemanticVersion: 1.0.0-beta
    SourceCodeUrl: https://github.com/pahud/lambda-layer-headless-chromium

Transform: AWS::Serverless-2016-10-31
Description: Create a Layer

Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      ContentUri: ./layer.zip
      CompatibleRuntimes: 
        - provided
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain

Outputs:
  LayerVersionArn:
    Description: ARN for the published Layer version
    Value: !Ref LambdaLayer
    Export:
      Name: !Sub 'LayerVersionArn-${AWS::StackName}'
