AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  WebhooktoHEC:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 3f4e25e0-1503-4053-9dac-f6a66a1da439
      Description: ''
      MemorySize: 128
      Timeout: 3
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /webhook-to-hec
            Method: ANY
