AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python MQTT Client.
Resources:
  fnPyMqtt:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 97ee542d-0376-48ba-8fd7-8f4f96773b5a
      Description: ''
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          iotendpoint: example.iot.us-east-1.amazonaws.com
