AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A starter AWS Lambda function.
Parameters:
  IdentityNameParameter:
    Type: String
Resources:
  helloworld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: c15ba5e3-f217-4c38-bbbd-67781c2e4932
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Policies:
      - SESSendBouncePolicy:
          IdentityName:
            Ref: IdentityNameParameter
