AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Bucket:
    Type: AWS::S3::Bucket
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python3.6
      CodeUri: lambda.zip
      Timeout: 300
      Environment:
        Variables:
          BUCKET: !Ref Bucket
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref Bucket
Outputs:
  BucketName:
    Description: Bucket Name
    Value: !Ref Bucket
  FunctionName:
    Description: Function Name
    Value: !Ref Function
