AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    NodeCanvasLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: canvas-nodejs
            Description: canvas@<CANVAS_VERSION>
            ContentUri: s3://<S3_BUCKET_NAME>/canvas-nodejs_v<CANVAS_VERSION>.zip
            CompatibleRuntimes:
                - nodejs<NODEJS_RUNTIME_VERSION>
            RetentionPolicy: Retain
            LicenseInfo: MIT
          
Outputs:
    LayerVersion:
        Description: Layer ARN Reference
        Value: !Ref NodeCanvasLayer
