AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  sns2chime:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sns2chime/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 5
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /incomingwebhooks/{proxy+}
            Method: ANY
