AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: f8075256-b31b-45ef-8cb2-ad3626165200
      Runtime: nodejs10.x
