AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  Name: alexa-skills-kit-nodejs-triviaskill
Transform: AWS::Serverless-2016-10-31
Resources:
  alexaskillskitnodejstriviaskill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK
      Timeout: 7
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 12de4848-a8dd-4bd9-9c85-0ce3ca485667
      Runtime: nodejs16.x
      MemorySize: 128
      Events:
        AlexaTrigger:
          Type: AlexaSkill
Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK