AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  SignalFxAuthToken:
    Type: String
  SelectedMetricGroups:
    Type: String
  Realm:
    Type: String
Resources:
  SignalFxProcessRDSMetrics:
    Type: AWS::Serverless::Function
    Properties:
      Handler: enhanced_rds.lambda_script.lambda_handler
      Runtime: python3.8
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: aa1d8241-a889-4d83-8d42-b53810b596ab
      Description: Parses RDS Enhanced Monitoring data from CloudWatch Logs and sends
        it to SignalFx.
      Timeout: 15
      Environment:
        Variables:
          access_token:
            Ref: SignalFxAuthToken
          groups:
            Ref: SelectedMetricGroups
          realm:
            Ref: Realm
