AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Available-ip-single-account
  Sample SAM Template for Available-ip
Globals:
  Function:
    Timeout: 3
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: cc177a50-90de-4641-bf79-d88cb1257958
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 300
