AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  eventbridge-integration-solution-aws-lambda
  (qs-1qon1a2rh)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Amazon EventBridge Integration Solution
      Parameters:
      - EventSourceName
    ParameterLabels:
      EventSourceName:
        default: Event Source Name
Parameters:
  EventSourceName:
    Type: String
    AllowedPattern: aws\.partner(/[\.\-_A-Za-z0-9]+){2,}
    MinLength: 1
    MaxLength: 256
    Description: Name of the Amazon EventBridge SaaS Partner Event Source to associate with an Event Bus. For example, aws.partner/example.com/1234567890/test-event-source.
Globals:
  Function:
    Timeout: 3
Resources:
  EventBridgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 30b7c491-206a-49e3-88d8-a970ea332fe6
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        EventBridgeRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              account:
              - Ref: AWS::AccountId
            EventBusName:
              Ref: EventBridgeEventBus
  EventBridgeEventBus:
    Type: AWS::Events::EventBus
    Properties:
      EventSourceName:
        Ref: EventSourceName
      Name:
        Ref: EventSourceName
Outputs:
  EventBridgeRule:
    Description: EventBridge Rule ARN
    Value:
      Fn::GetAtt:
      - EventBridgeFunctionEventBridgeRule
      - Arn
  EventBridgeFunction:
    Description: EventBridge Lambda Function ARN
    Value:
      Fn::GetAtt:
      - EventBridgeFunction
      - Arn
  EventBridgeFunctionIamRole:
    Description: Implicit IAM Role created for EventBridge function
    Value:
      Fn::GetAtt:
      - EventBridgeFunctionRole
      - Arn
