AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 6ec034bf-3425-4d56-89b8-a7140b66aa2e
      Runtime: python3.6
      Handler: index.handler
      MemorySize: 1024
      Timeout: 30