Transform: AWS::Serverless-2016-10-31
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: signalfx-lambda-nodejs-wrapper
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 277c6c08-6067-43a7-ab53-2669d215deb7
      CompatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
Outputs:
  LayerArn:
    Value:
      Ref: SharedLayer
