AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      Runtime: python3.7
      Timeout: 900
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 7e9c0b7b-2a8b-4840-acaa-9b0f5286d419
