AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This SAM Application provides the base Lambda Layers to run PHP projects as Lambda Functions
Resources:
  PhpBinLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: php-74
      Description: This layer provides PHP and Composer binaries under /opt/bin/
      CompatibleRuntimes:
      - provided
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 37d5791e-6a02-47e2-872c-f7b83eda3f42
  LatestPhpBinLayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: latest-php-74-lambda-layer
      Type: String
      Value:
        Ref: PhpBinLayer
Outputs:
  PhpBinLayerArn:
    Value:
      Ref: PhpBinLayer
    Description: ARN of the latest PHP bin layer
