AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Available-ip-cross-account
  Sample SAM Template for Available-ip
Globals:
  Function:
    Timeout: 3
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: b2cd2dd4-3a48-4e04-802e-bea24e478a3d
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 300
