AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  AWS Data Wrangler Lambda Layer (Python 3.8 | Arm64)
Parameters:
  LayerName:
    Description: Name of the Layer
    Type: String
    Default: AWSDataWrangler-Python38-Arm64
  ExportName:
    Description: Name of the export
    Type: String
    Default: aws-data-wrangler-py3-8-arm64
Resources:
  WranglerLayer38:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Ref: LayerName
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: d3f541d2-f735-4113-9819-e1969425d5a1
      Description: AWS Data Wrangler Lambda Layer - 2.16.1 (Python 3.8 | Arm64)
      LicenseInfo: Apache 2.0
      CompatibleRuntimes:
      - python3.8
    Metadata:
      SamResourceId: WranglerLayer38
Outputs:
  WranglerLayer38Arn:
    Value:
      Ref: WranglerLayer38
    Export:
      Name:
        Ref: ExportName
