AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 1.0.5
Resources:
  apitoec2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 94db9f19-884f-43aa-a089-cf620ee10b58
      Description: 1.0.5
      MemorySize: 128
      Timeout: 10
      Role: arn:aws:iam::140283274032:role/api-to-ec2
