AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdafunctionforheadlesschromeawsnsu:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 50b0076b-f805-4185-86b4-8ee647322788
      Description: ''
      MemorySize: 1280
      Timeout: 900
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(30 14 * * ? *)
      Layers:
      - arn:aws:lambda:ap-northeast-1:285678482385:layer:headless:1
      - arn:aws:lambda:ap-northeast-1:285678482385:layer:selenium:1
      - arn:aws:lambda:ap-northeast-1:113088814899:layer:Klayers-python37-beautifulsoup4:12
