AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  streamdataiogithubsearchcode:
    Type: AWS::Serverless::Function
    Properties:
      Description: Streamdata.io Github Code Search Streaming to Amazon S3 Data Lake Using Lambda
      MemorySize: 128
      Environment:
        Variables:
          appToken: Streamdata.io-Application-Token
          s3bucket: streaming-data-lake
          targetUrl: https://api.github.com/search/code
          query: postman collections
          github_token: Github-Token
          targetFolder: github-search-code
      Handler: index.handler
      Timeout: 63
      Policies:
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Resource:
            Fn::Sub:
            - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
            - functionName: streamdata-io-github-search-code
          Effect: Allow
      - Statement:
        - Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:GetBucketLocation
          - s3:GetObjectVersion
          - s3:PutObject
          - s3:GetLifecycleConfiguration
          - s3:PutLifecycleConfiguration
          Resource:
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}
            - bucketName: streaming-data-lake
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}/*
            - bucketName: streaming-data-lake
          Effect: Allow
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 7b1426de-6ced-4ce5-b1ad-7e3c1deb9604
      Runtime: nodejs6.10
Description: Streamdata.io Github Code Search Streaming to Amazon S3 Data Lake Using Lambda
