AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Environment variables"
        Parameters:
          - 01-SERVER
          - 02-DATABASE
          - 03-FIELD
          - 04-LAYOUT
          - 05-ACCOUNT
          - 06-PASSWORD
    ParameterLabels:
      01SERVER:
        default: "SERVER"
      02DATABASE:
        default: "DATABASE"
      03FIELD:
        default: "FIELD"
      04LAYOUT:
        default: "LAYOUT"
      05ACCOUNT:
        default: "ACCOUNT"
      06PASSWORD:
        default: "PASSWORD"
Parameters:
  01SERVER:
    Description: The URL of the server where the database is hosted. Include either http:// or https://.
    Type: String
    AllowedPattern: "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)"
  02DATABASE:
    Description: Name of the Filemaker database where the button JSON will be saved.
    Type: String
  03FIELD:
    Description: Name of the FileMaker field where the button JSON will be saved.
    Type: String
  04LAYOUT:
    Description: Name of the Filemaker layout that contains FIELD.
    Type: String
  05ACCOUNT:
    Description: Name of an account that has fmrest (Data API) privileges.
    Type: String
    NoEcho: true
  06PASSWORD:
    Description: The password for ACCOUNT above.
    Type: String
    NoEcho: true
Resources:
  rev11attiotbuttonfilemakerapi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'A lambda function to post JSON generated by a 1 click event to a FileMaker Database via the Filemaker Data API'
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs8.10
      Timeout: 3
      CodeUri: 's3://revolution11fmiapi/rev11attiotbuttonfilemakerapi.zip'
      Environment:
        Variables:
          SERVER: !Ref 01SERVER
          DATABASE: !Ref 02DATABASE
          FIELD: !Ref 03FIELD
          LAYOUT: !Ref 04LAYOUT
          ACCOUNT: !Ref 05ACCOUNT
          PASSWORD: !Ref 06PASSWORD