AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Docker image scanning automation.
  AWS ECR registry push event based DSSC scan.
  This serverless application integrates with Trend Micro deep security smart check using its APIs and sends image details to initiate security scan that is received from AWS cloud watch events.
Globals:
  Function:
    Timeout: 3
Resources:
  EcrDsscScanEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 5f04427d-2641-4405-8672-848c345ddcd8
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          AWS_ECR_ACCESS: <AWS_ACCESS_KEY_FOR_ECR_ACCESS>
          AWS_ECR_SECRET: <AWS_SECRET_KEY_FOR_ECR_ACCESS>
          DSSC_URL: <DSSC_URL>
          DSSC_PSW: <DSSC_USER_PASSWORD>
          DSSC_USER: <DSSC_USER_FOR_ECR_AUTOMATION>
      Events:
        Cloudwatch:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.ecr
              detail-type:
              - ECR Image Action
Outputs:
  EcrDsscScanEvent:
    Description: Deep Security Lambda Function ARN for AWS ECR scan with DSSC automation function
    Value:
      Fn::GetAtt:
      - EcrDsscScanEvent
      - Arn
