Transform: AWS::Serverless-2016-10-31
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: signalfx-lambda-python-wrapper
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: ac399cfb-3b57-4b72-a095-f3f34fc29169
      CompatibleRuntimes:
      - python2.7
      - python3.6
      - python3.7
      - python3.8
Outputs:
  LayerArn:
    Value:
      Ref: SharedLayer
