AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  streamdataiogithubsearchissues:
    Type: AWS::Serverless::Function
    Properties:
      Description: Streamdata.io Github Issues Search Streaming to Amazon S3 Data Lake Using Lambda
      MemorySize: 128
      Environment:
        Variables:
          appToken: Streamdata.io-Application-Token
          s3bucket: streaming-data-lake
          targetUrl: https://api.github.com/search/issues
          query: postman collections
          github_token: Github-Token
          targetFolder: github-search-issues
      Handler: index.handler
      Timeout: 63
      Policies:
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Resource:
            Fn::Sub:
            - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
            - functionName: streamdata-io-github-search-issues
          Effect: Allow
      - Statement:
        - Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:GetBucketLocation
          - s3:GetObjectVersion
          - s3:PutObject
          - s3:GetLifecycleConfiguration
          - s3:PutLifecycleConfiguration
          Resource:
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}
            - bucketName: streaming-data-lake
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}/*
            - bucketName: streaming-data-lake
          Effect: Allow
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 322968f5-7a2b-4eff-ae5d-bbc5566bef3d
      Runtime: nodejs6.10
Description: Streamdata.io Github Issues Search Streaming to Amazon S3 Data Lake Using Lambda
