Transform: AWS::Serverless-2016-10-31
Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      __MANAGE_SWAGGER: true
      DefinitionBody:
        info:
          version: '1.0'
          title:
            Ref: AWS::StackName
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetBlockNumber.Arn}/invocations
              responses: {}
        swagger: '2.0'
      StageName: Prod
  GetBlockNumber:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 0039632c-3eb2-4690-9503-4549d0b0cff2
      Handler: blockNumber.handler
      Events:
        GetBlockNumberEndpoint:
          Type: Api
          Properties:
            Path: /
            RestApiId:
              Ref: ServerlessRestApi
            Method: GET
      Runtime: nodejs8.10
