AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless BibCard
Globals:
  Function:
    Timeout: 30
Resources:
  BibCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 4b031425-2897-496e-a67c-5072e86bf1f6
      Handler: lambda_function.lambda_handler
      Runtime: ruby2.7
      Layers:
      - arn:aws:lambda:us-east-1:523567452838:layer:BibCard-Dependencies:3
      Events:
        ExplicitApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: HttpApi
            Method: GET
            Path: /
            PayloadFormatVersion: '2.0'
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
        - '*'
Outputs:
  HttpApiUrl:
    Description: URL of the BibCard API endpoint
    Value:
      Fn::Sub: https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/
