AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  streamdataiogithuborgevents:
    Type: AWS::Serverless::Function
    Properties:
      Description: Streamdata.io Github Organization Events Streaming to Amazon S3 Data Lake Using Lambda
      MemorySize: 128
      Environment:
        Variables:
          github_org: guardian
          appToken: Streamdata.io-Application-Token
          s3bucket: streaming-data-lake
          targetUrl: https://api.github.com/orgs/{org}/events
          github_token: Github-Token
          targetFolder: github-org-events
      Handler: index.handler
      Timeout: 60
      Policies:
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Resource:
            Fn::Sub:
            - arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*
            - functionName: streamdata-io-github-org-events
          Effect: Allow
      - Statement:
        - Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:GetBucketLocation
          - s3:GetObjectVersion
          - s3:PutObject
          - s3:GetLifecycleConfiguration
          - s3:PutLifecycleConfiguration
          Resource:
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}
            - bucketName: streaming-data-lake
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}/*
            - bucketName: streaming-data-lake
          Effect: Allow
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 1a7ce572-4943-4c6d-9201-e10d865746f6
      Runtime: nodejs6.10
Description: Streamdata.io Github Organization Events Streaming to Amazon S3 Data Lake Using Lambda
