AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  Name: Alexa-Nodejs-14x-Template
Transform: AWS::Serverless-2016-10-31
Resources:
  code:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Description: Alexa Base Template with ask-sdk-core and Node.js 14.x Support
      Timeout: 7
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 0a18b4cd-f338-432a-ad6f-2b6a3ae15094
      Runtime: nodejs14.x
      MemorySize: 128
      Events:
        AlexaTrigger:
          Type: AlexaSkill
Description: Alexa Base Template with ask-sdk-core and Node.js 14.x Support
