AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function extension for logging to Coralogix.
Parameters:
  CompatibleRuntimes:
    Type: CommaDelimitedList
    Description: Lambda Layer Version compatible runtimes
    Default: go1.x, nodejs16.x, nodejs18.x, python3.8, python3.9
  AMD64SupportEnabled:
    Type: String
    Description: Enable support of AMD64 lambdas
    AllowedValues:
    - true
    - false
    Default: true
  ARM64SupportEnabled:
    Type: String
    Description: Enable support of ARM64 lambdas
    AllowedValues:
    - true
    - false
    Default: false
  RetentionPolicy:
    Type: String
    Description: Lambda Layer Version retention policy
    AllowedValues:
    - Retain
    - Delete
    Default: Retain
Conditions:
  IsAMD64SupportEnabled:
    Fn::Equals:
    - Ref: AMD64SupportEnabled
    - true
  IsARM64SupportEnabled:
    Fn::Equals:
    - Ref: ARM64SupportEnabled
    - true
Resources:
  LambdaLayerAMD64Version:
    Type: AWS::Serverless::LayerVersion
    Condition: IsAMD64SupportEnabled
    Properties:
      LayerName: coralogix-extension-x86_64
      Description: Lambda function extension for logging to Coralogix (x86_64)
      LicenseInfo: Apache-2.0
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 139ace11-b1ac-4538-92c2-a2e2b805d1fc
      CompatibleRuntimes:
        Ref: CompatibleRuntimes
      CompatibleArchitectures:
      - x86_64
      RetentionPolicy:
        Ref: RetentionPolicy
    Metadata:
      SamResourceId: LambdaLayerAMD64Version
  LambdaLayerARM64Version:
    Type: AWS::Serverless::LayerVersion
    Condition: IsARM64SupportEnabled
    Properties:
      LayerName: coralogix-extension-arm64
      Description: Lambda function extension for logging to Coralogix (arm64)
      LicenseInfo: Apache-2.0
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 6d2f5ed0-f2b3-493a-a24a-37f49be9f9b4
      CompatibleRuntimes:
        Ref: CompatibleRuntimes
      CompatibleArchitectures:
      - arm64
      RetentionPolicy:
        Ref: RetentionPolicy
    Metadata:
      SamResourceId: LambdaLayerARM64Version
Outputs:
  LambdaLayerAMD64VersionArn:
    Description: Lambda Layer version ARN for coralogix-extension (x86_64)
    Condition: IsAMD64SupportEnabled
    Value:
      Ref: LambdaLayerAMD64Version
    Export:
      Name: CORALOGIX-EXTENSION-AMD64
  LambdaLayerARM64VersionArn:
    Description: Lambda Layer version ARN for coralogix-extension (arm64)
    Condition: IsARM64SupportEnabled
    Value:
      Ref: LambdaLayerARM64Version
    Export:
      Name: CORALOGIX-EXTENSION-ARM64
