AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An Amazon Kinesis Firehose stream processor that converts input records from Apache Common Log format to CSV.
Parameters:
  FunctionNameParameter:
    Type: String
  TableNameParameter:
    Type: String
Resources:
  kinesisfirehoseapachelogtocsv:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 2ec70b70-de8e-4945-aae4-27e2ef9bbd9e
      Description: An Amazon Kinesis Firehose stream processor that converts input records from Apache Common Log format to CSV.
      MemorySize: 128
      Timeout: 3
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: FunctionNameParameter
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableNameParameter